# Generated by Django 2.2 on 2019-04-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_kwatts', models.PositiveIntegerField(help_text='Kilowatts consumidos indicador 1.8')),
                ('generado_kwatts', models.PositiveIntegerField(help_text='Kilowatts generados indicador 2.8')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualizacion', null=True)),
            ],
            options={
                'verbose_name': 'registro_energia',
                'verbose_name_plural': 'registros_energia',
            },
        ),
    ]
